import type { Metadata } from "next";
import { Assistant } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";

const assistant = Assistant({
  subsets: ["hebrew", "latin"],
  variable: "--font-assistant",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl">
      <body
        className={`${assistant.className} antialiased bg-zinc-50 dark:bg-black text-zinc-900 dark:text-zinc-50 flex min-h-screen`}
      >
        <Sidebar />
        <main className="flex-1 w-full min-h-screen flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
